[project]
name = "fpl-team-picker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ortools>=9.14.6206",
    "pandas>=2.3.2",
    "streamlit>=1.49.0",
]
